plugins {
	id 'com.android.application'
}

android {
	compileSdk 37

	defaultConfig {
		applicationId "be.ntmn.inficam"
		minSdkVersion 24
		versionCode 4
		versionName "1.0.5"
		vectorDrawables.useSupportLibrary true // To support older minSdk

		/* We need targetSdkVersion <= 27 for some Android 10 devices to work:
		 *   https://issuetracker.google.com/issues/145082934
		 *   https://issuetracker.google.com/issues/139087809
		 */
		//noinspection ExpiredTargetSdkVersion
		targetSdkVersion 34
	}

	buildTypes {
		debug {
			debuggable true
		}
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
			signingConfig signingConfigs.debug
		}
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}

    namespace 'be.ntmn.inficam'
    lint {
        checkReleaseBuilds false
    }

	packaging {
		jniLibs {
			keepDebugSymbols += "**/*.so"   // or "**/arm64-v8a/*.so"
		}
	}
}

dependencies {
	implementation 'androidx.appcompat:appcompat:1.4.1'
	implementation 'com.google.android.material:material:1.5.0'
	implementation project(path: ':libinficam')
}
